### ISSUE TITLE
弄一个小小的界面。参考 coinbase 的界面

### ISSUE THREAD

**Issue by laalaguer** [laalaguer/CoinTracker#3]
有各个交易对的信息
然后有简单的曲线，有最后一次读取的时间

**Comment by laalaguer** [comment]
![artboard](https://user-images.githubusercontent.com/6841046/36527851-23b29a5e-17ee-11e8-8ac1-34ba8d121184.png)
![1519287455215](https://user-images.githubusercontent.com/6841046/36527865-2cb75b1c-17ee-11e8-9f02-9be9a92dd14b.jpg)

**Comment by yanpu-si** [comment]
:)
